name: 'SonarQube Scan'
description: 'Scan your code with SonarQube Scanner to detect bugs, vulnerabilities and code smells.'
author: 'YND'
branding:
  icon: 'check'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  host:
    description: 'SonarQube server URL'
    required: true
  projectBaseDir:
    description: 'Location of the code to analyze'
    required: false
    default: '.'
  token:
    description: 'Authentication token of a SonarQube user'
    required: true
  projectKey:
    description: 'Project key in SonarQube Server.'
    required: true
